services:
  node_cli:
    image: zcodeapp/node
    build:
      context: ${PWD}
      dockerfile: docker/node/Dockerfile
    volumes:
      - ${PWD}:/var/www

  quasar_dev:
    image: zcodeapp/node
    depends_on:
      - node_cli
    entrypoint: /usr/local/bin/npx
    command: quasar dev --port 3000 --hostname 0.0.0.0
    volumes:
      - ${PWD}:/var/www
    ports:
      - 3000:3000