services:
  node_cli:
    image: zcodeapp/node_frontend
    build:
      context: ${PWD}
      dockerfile: docker/node/Dockerfile
    volumes:
      - ${PWD}:/var/www/ide
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VITE_PROTOCOL=http
      - VITE_DOMAIN=localhost
      - VITE_PORT=3000
      - VITE_IDE_VERSION=0.0.5
      - VITE_SERVER_ADDRESS=ws://localhost
      - VITE_SERVER_PORT=4000
      - VITE_SERVER_KEY=355b5636-3c3e-4e57-97ad-5e1dd40283a2
      - VITE_SERVER_TIMEOUT=5000
    network_mode: host

  node_cypress:
    image: zcodeapp/node_cypress
    build:
      context: ${PWD}
      dockerfile: docker/cypress/Dockerfile
    ports:
      - 8080:8080
      - 9000:9000
    environment:
      - DISPLAY=${DISPLAY}
      - VITE_PROTOCOL=http
      - VITE_DOMAIN=localhost
      - VITE_PORT=3000
      - VITE_IDE_VERSION=0.0.5
      - VITE_SERVER_ADDRESS=ws://localhost
      - VITE_SERVER_PORT=4000
      - VITE_SERVER_KEY=355b5636-3c3e-4e57-97ad-5e1dd40283a2
      - VITE_SERVER_TIMEOUT=5000
    volumes:
      - ${PWD}:/e2e
      - ~/.cache/Cypress:/home/node/.cache/Cypress
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host