services:
  node_cli:
    image: zcodeapp/node
    build:
      context: ${PWD}
      dockerfile: docker/node/Dockerfile
    volumes:
      - ${PWD}:/var/www

  quasar_dev:
    image: zcodeapp/node
    build:
      context: ${PWD}
      dockerfile: docker/node/Dockerfile
    entrypoint: /usr/local/bin/npx
    command: quasar dev --port 3000 --hostname 0.0.0.0
    volumes:
      - ${PWD}:/var/www
    ports:
      - 3000:3000
    environment:
      - VITE_PROTOCOL=http
      - VITE_DOMAIN=localhost
      - VITE_PORT=3000
      - VITE_IDE_VERSION=0.0.1-alpha
      - VITE_SERVER_ADDRESS=ws://localhost
      - VITE_SERVER_PORT=4000

  node_cypress:
    image: zcodeapp/node_cypress
    build:
      context: ${PWD}
      dockerfile: docker/cypress/Dockerfile
    ports:
      - 8080:8080
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ${PWD}:/e2e
      - ~/.cache/Cypress:/home/node/.cache/Cypress
      - /tmp/.X11-unix:/tmp/.X11-unix