name: ZCode App IDE
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - "main"
jobs:
  install:
    name: Install development
    runs-on: ubuntu-latest
    environment: development
    container:
      image: zcodeapp/node_frontend
      options: --user root
    env:
      NODE_ENV: development
      VITE_DOMAIN: '${{ secrets.VITE_DOMAIN }}'
      VITE_IDE_VERSION: '${{ secrets.VITE_IDE_VERSION }}'
      VITE_PORT: '${{ secrets.VITE_PORT }}'
      VITE_PROTOCOL: '${{ secrets.VITE_PROTOCOL }}'
      VITE_SERVER_ADDRESS: '${{ secrets.VITE_SERVER_ADDRESS }}'
      VITE_SERVER_PORT: '${{ secrets.VITE_SERVER_PORT }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: "bin/ci/install -e development"
      - name: Build
        run: "VITE_DOMAIN=$VITE_DOMAIN VITE_IDE_VERSION=$VITE_IDE_VERSION VITE_PORT=$VITE_PORT VITE_PROTOCOL=$VITE_PROTOCOL VITE_SERVER_ADDRESS=$VITE_SERVER_ADDRESS VITE_SERVER_PORT=$VITE_SERVER_PORT bin/ci/build -e development"
      - name: Cache Install
        id: cache-install
        uses: actions/cache/save@v3
        with:
          path: .
          key: ${{ runner.os }}-install-${{ github.sha }}
      - name: Cache Node
        id: cache-node
        uses: actions/cache/save@v3
        with:
          path: /github/home/.cache
          key: ${{ runner.os }}-install-cache-${{ github.sha }}

  test_unit:
    name: Test Unit
    runs-on: ubuntu-latest
    needs:
    - install
    environment: development
    container:
      image: zcodeapp/node_frontend
      options: --user root
    env:
      NODE_ENV: development
    steps:
      - name: Restore Install
        id: cache-install
        uses: actions/cache/restore@v3
        with:
          path: .
          key: ${{ runner.os }}-install-${{ github.sha }}
      - name: Restore Node
        id: cache-node
        uses: actions/cache/restore@v3
        with:
          path: /github/home/.cache
          key: ${{ runner.os }}-install-cache-${{ github.sha }}
      - name: Test
        run: "bin/ci/test_unit -e development"

  test_e2e:
    name: Test e2e
    runs-on: ubuntu-latest
    needs:
    - install
    environment: development
    container:
      image: zcodeapp/node_cypress
      options: --user root
    env:
      NODE_ENV: development
    steps:
      - name: Restore Install
        id: cache-install
        uses: actions/cache/restore@v3
        with:
          path: .
          key: ${{ runner.os }}-install-${{ github.sha }}
      - name: Restore Node
        id: cache-node
        uses: actions/cache/restore@v3
        with:
          path: /github/home/.cache
          key: ${{ runner.os }}-install-cache-${{ github.sha }}
      - name: Test
        run: "bin/ci/test_e2e -e development"
    
  install_production:
    name: Install production
    runs-on: ubuntu-latest
    needs:
    - test_unit
    - test_e2e
    environment: development
    container:
      image: zcodeapp/node_frontend
      options: --user root
    env:
      NODE_ENV: development
      VITE_DOMAIN: '${{ secrets.VITE_DOMAIN }}'
      VITE_IDE_VERSION: '${{ secrets.VITE_IDE_VERSION }}'
      VITE_PORT: '${{ secrets.VITE_PORT }}'
      VITE_PROTOCOL: '${{ secrets.VITE_PROTOCOL }}'
      VITE_SERVER_ADDRESS: '${{ secrets.VITE_SERVER_ADDRESS }}'
      VITE_SERVER_PORT: '${{ secrets.VITE_SERVER_PORT }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: "bin/ci/install -e production"
      - name: Build
        run: "VITE_DOMAIN=$VITE_DOMAIN VITE_IDE_VERSION=$VITE_IDE_VERSION VITE_PORT=$VITE_PORT VITE_PROTOCOL=$VITE_PROTOCOL VITE_SERVER_ADDRESS=$VITE_SERVER_ADDRESS VITE_SERVER_PORT=$VITE_SERVER_PORT bin/ci/build -e production"
      - name: Cache
        id: cache-install-production
        uses: actions/cache/save@v3
        with:
          path: .
          key: ${{ runner.os }}-install-production-${{ github.sha }}

  image:
    name: Create image
    runs-on: ubuntu-latest
    needs:
    - install_production
    environment: development
    container:
      image: zcodeapp/node_frontend
      options: --user root
    steps:
      - name: Restore Install
        id: cache-install-production
        uses: actions/cache/restore@v3
        with:
          path: .
          key: ${{ runner.os }}-install-production-${{ github.sha }}
      - name: Create Image
        run: "bin/ci/image -e production -d zcodeapp/ide"
      - name: Save Image
        run: mkdir images && docker image save --output images/zcodeapp-ide.tar zcodeapp/ide
      - name: Cache Image
        id: cache-image
        uses: actions/cache/save@v3
        with:
          path: images
          key: ${{ runner.os }}-image-${{ github.sha }}

  test_container:
    name: Test e2e Container
    runs-on: ubuntu-latest
    needs:
    - image
    environment: development
    container:
      image: zcodeapp/node_frontend
      options: --user root
    env:
      NODE_ENV: development
    steps:
      - name: Restore Install
        id: cache-install
        uses: actions/cache/restore@v3
        with:
          path: .
          key: ${{ runner.os }}-install-${{ github.sha }}
      - name: Restore Image
        id: cache-image
        uses: actions/cache/restore@v3
        with:
          path: images
          key: ${{ runner.os }}-image-${{ github.sha }}
      - name: Import Image
        run: docker image load -i images/zcodeapp-ide.tar
      - name: Image Tag
        run: docker tag zcodeapp/ide:latest zcodeapp/ide:test_version
      - name: Start ZCode APP IDE
        uses: zcodeapp/ide-github-action@1.0.2
        with:
          ide-version: test_version
      - name: Test Image
        run: "bin/ci/test_container -e development"
